version: "3.0"
services:
  shark_db:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    ports:
      - "3306:3306"
  shark_app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    ports:
      - "22:22"
    tty: true
    volumes:
      - .:/home/ipshark
  shark_redis:
    image: "redis"
    ports:
      - "6379:6379"
    depends_on:
      - shark_php_fpm
  shark_beanstalkd:
    build:
      context: .
      dockerfile: docker/beanstalkd.Dockerfile
    ports:
      - "11300:11300"
    privileged: true
    depends_on:
      - shark_php_fpm
  shark_worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    depends_on:
      - shark_app
    links:
      - shark_beanstalkd
      - shark_redis
      - shark_db
    ports:
      - "6001:6001"
    volumes:
      - .:/home/ipshark
  shark_web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    depends_on:
      - shark_app
    links:
      - shark_php_fpm
      - shark_db
    restart: always
    volumes:
      - .:/var/log/nginx
      - .:/etc/nginx/sites-available
      - .:/home/ipshark
    ports:
      - "80:80"
      - "443:443"
  shark_php_fpm:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    depends_on:
      - shark_app
    links:
      - shark_db
    expose:
      - "9000"
    volumes:
      - .:/home/ipshark
