version: "3.0"
services:
  shark_test:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
      image: ipshark/shark-test
  shark_db:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
      image: ipshark/shark-db
  shark_redis:
    image: "redis"
  shark_worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
      image: ipshark/shark-worker
    links:
      - shark_redis
      - shark_db
    volumes:
      - .:/home/ipshark
  shark_main:
    build:
      context: .
      dockerfile: docker/main.Dockerfile
      image: ipshark/shark-main
    links: 
      - shark_db
      - shark_redis
      - shark_worker
    volumes:
      - .:/home/ipshark

